// src/lib/utils/passportCountryMappings.ts

export const countryMappings = [
  { patterns: [/UNITED\s+STATES\s+OF\s+AMERICA/i, /\bUSA\b/, /\bU\.?S\.?A\.?\b/i, /UNITED\s+STATES/i], country: 'United States' },
  { patterns: [/CANADA/i, /\bCAN\b/], country: 'Canada' },
  { patterns: [/UNITED\s+KINGDOM/i, /\bGBR\b/, /\bUK\b/, /GREAT\s+BRITAIN/i], country: 'United Kingdom' },
  { patterns: [/FRANCE/i, /\bFRA\b/, /RÉPUBLIQUE\s+FRANÇAISE/i], country: 'France' },
  { patterns: [/GERMANY/i, /\bDEU\b/, /DEUTSCHLAND/i], country: 'Germany' },
  { patterns: [/AUSTRALIA/i, /\bAUS\b/], country: 'Australia' },
  { patterns: [/JAPAN/i, /\bJPN\b/, /日本国/], country: 'Japan' },
  { patterns: [/CHINA/i, /\bCHN\b/, /中华人民共和国/], country: 'China' },
  { patterns: [/INDIA/i, /\bIND\b/], country: 'India' },
  { patterns: [/BRAZIL/i, /\bBRA\b/, /BRASIL/i], country: 'Brazil' },
  { patterns: [/MEXICO/i, /\bMEX\b/, /MÉXICO/i], country: 'Mexico' },
  { patterns: [/ITALY/i, /\bITA\b/, /ITALIA/i], country: 'Italy' },
  { patterns: [/SPAIN/i, /\bESP\b/, /ESPAÑA/i], country: 'Spain' },
  { patterns: [/NETHERLANDS/i, /\bNLD\b/, /NEDERLAND/i], country: 'Netherlands' },
  { patterns: [/BELGIUM/i, /\bBEL\b/, /BELGIQUE/i, /BELGIË/i], country: 'Belgium' },
  { patterns: [/SWITZERLAND/i, /\bCHE\b/, /SUISSE/i, /SCHWEIZ/i], country: 'Switzerland' },
  { patterns: [/AUSTRIA/i, /\bAUT\b/, /ÖSTERREICH/i], country: 'Austria' },
  { patterns: [/SWEDEN/i, /\bSWE\b/, /SVERIGE/i], country: 'Sweden' },
  { patterns: [/NORWAY/i, /\bNOR\b/, /NORGE/i], country: 'Norway' },
  { patterns: [/DENMARK/i, /\bDNK\b/, /DANMARK/i], country: 'Denmark' },
  { patterns: [/FINLAND/i, /\bFIN\b/, /SUOMI/i], country: 'Finland' },
  { patterns: [/POLAND/i, /\bPOL\b/, /POLSKA/i], country: 'Poland' },
  { patterns: [/PORTUGAL/i, /\bPRT\b/], country: 'Portugal' },
  { patterns: [/GREECE/i, /\bGRC\b/, /ΕΛΛΆΔΑ/i], country: 'Greece' },
  { patterns: [/TURKEY/i, /\bTUR\b/, /TÜRKİYE/i], country: 'Turkey' },
  { patterns: [/RUSSIA/i, /\bRUS\b/, /РОССИЙСКАЯ/i], country: 'Russia' },
  { patterns: [/UKRAINE/i, /\bUKR\b/, /УКРАЇНА/i], country: 'Ukraine' },
  { patterns: [/SOUTH\s+KOREA/i, /\bKOR\b/, /REPUBLIC\s+OF\s+KOREA/i, /대한민국/], country: 'South Korea' },
  { patterns: [/SINGAPORE/i, /\bSGP\b/], country: 'Singapore' },
  { patterns: [/NEW\s+ZEALAND/i, /\bNZL\b/], country: 'New Zealand' },
  { patterns: [/IRELAND/i, /\bIRL\b/, /ÉIRE/i], country: 'Ireland' },
  { patterns: [/ISRAEL/i, /\bISR\b/, /ישראל/], country: 'Israel' },
  { patterns: [/SOUTH\s+AFRICA/i, /\bZAF\b/], country: 'South Africa' },
  { patterns: [/ARGENTINA/i, /\bARG\b/], country: 'Argentina' },
  { patterns: [/CHILE/i, /\bCHL\b/], country: 'Chile' },
  { patterns: [/COLOMBIA/i, /\bCOL\b/], country: 'Colombia' },
  { patterns: [/PERU/i, /\bPER\b/, /PERÚ/i], country: 'Peru' },
  { patterns: [/VENEZUELA/i, /\bVEN\b/], country: 'Venezuela' },
  { patterns: [/EGYPT/i, /\bEGY\b/, /مصر/], country: 'Egypt' },
  { patterns: [/SAUDI\s+ARABIA/i, /\bSAU\b/, /السعودية/], country: 'Saudi Arabia' },
  { patterns: [/UNITED\s+ARAB\s+EMIRATES/i, /\bARE\b/, /UAE/i], country: 'United Arab Emirates' },
  { patterns: [/THAILAND/i, /\bTHA\b/, /ประเทศไทย/], country: 'Thailand' },
  { patterns: [/MALAYSIA/i, /\bMYS\b/], country: 'Malaysia' },
  { patterns: [/INDONESIA/i, /\bIDN\b/], country: 'Indonesia' },
  { patterns: [/PHILIPPINES/i, /\bPHL\b/, /PILIPINAS/i], country: 'Philippines' },
  { patterns: [/VIETNAM/i, /\bVNM\b/, /VIỆT\s+NAM/i], country: 'Vietnam' },
  { patterns: [/PAKISTAN/i, /\bPAK\b/], country: 'Pakistan' },
  { patterns: [/BANGLADESH/i, /\bBGD\b/], country: 'Bangladesh' },
  { patterns: [/NIGERIA/i, /\bNGA\b/], country: 'Nigeria' },
  { patterns: [/KENYA/i, /\bKEN\b/], country: 'Kenya' },
  { patterns: [/MOROCCO/i, /\bMAR\b/, /المغرب/], country: 'Morocco' },
  { patterns: [/TUNISIA/i, /\bTUN\b/, /تونس/], country: 'Tunisia' },
  { patterns: [/ALGERIA/i, /\bDZA\b/, /الجزائر/], country: 'Algeria' },
  { patterns: [/CZECH\s+REPUBLIC/i, /\bCZE\b/, /ČESKÁ\s+REPUBLIKA/i], country: 'Czech Republic' },
  { patterns: [/HUNGARY/i, /\bHUN\b/, /MAGYARORSZÁG/i], country: 'Hungary' },
  { patterns: [/ROMANIA/i, /\bROU\b/, /ROMÂNIA/i], country: 'Romania' },
  { patterns: [/BULGARIA/i, /\bBGR\b/, /БЪЛГАРИЯ/i], country: 'Bulgaria' },
  { patterns: [/SLOVAKIA/i, /\bSVK\b/, /SLOVENSKO/i], country: 'Slovakia' },
  { patterns: [/CROATIA/i, /\bHRV\b/, /HRVATSKA/i], country: 'Croatia' },
  { patterns: [/SERBIA/i, /\bSRB\b/, /СРБИЈА/i], country: 'Serbia' },
  { patterns: [/LITHUANIA/i, /\bLTU\b/, /LIETUVA/i], country: 'Lithuania' },
  { patterns: [/LATVIA/i, /\bLVA\b/, /LATVIJA/i], country: 'Latvia' },
  { patterns: [/ESTONIA/i, /\bEST\b/, /EESTI/i], country: 'Estonia' },
  { patterns: [/ICELAND/i, /\bISL\b/, /ÍSLAND/i], country: 'Iceland' },
  { patterns: [/LUXEMBOURG/i, /\bLUX\b/], country: 'Luxembourg' },
  { patterns: [/MALTA/i, /\bMLT\b/], country: 'Malta' },
  { patterns: [/CYPRUS/i, /\bCYP\b/, /ΚΎΠΡΟΣ/i], country: 'Cyprus' },
  { patterns: [/SLOVENIA/i, /\bSVN\b/, /SLOVENIJA/i], country: 'Slovenia' },
  { patterns: [/ALBANIA/i, /\bALB\b/, /SHQIPËRI/i], country: 'Albania' },
  { patterns: [/MONTENEGRO/i, /\bMNE\b/, /CRNA\s+GORA/i], country: 'Montenegro' },
  { patterns: [/BOSNIA\s+AND\s+HERZEGOVINA/i, /\bBIH\b/, /BOSNA\s+I\s+HERCEGOVINA/i], country: 'Bosnia and Herzegovina' },
  { patterns: [/NORTH\s+MACEDONIA/i, /\bMKD\b/, /МАКЕДОНИЈА/i], country: 'North Macedonia' },
  { patterns: [/ARMENIA/i, /\bARM\b/, /ՀԱՅԱՍՏԱՆ/i], country: 'Armenia' },
  { patterns: [/AZERBAIJAN/i, /\bAZE\b/, /AZƏRBAYCAN/i], country: 'Azerbaijan' },
  { patterns: [/GEORGIA/i, /\bGEO\b/, /საქართველო/i], country: 'Georgia' },
  { patterns: [/KAZAKHSTAN/i, /\bKAZ\b/, /ҚАЗАҚСТАН/i], country: 'Kazakhstan' },
  { patterns: [/UZBEKISTAN/i, /\bUZB\b/, /O'ZBEKISTON/i], country: 'Uzbekistan' },
  { patterns: [/KYRGYZSTAN/i, /\bKGZ\b/, /КЫРГЫЗСТАН/i], country: 'Kyrgyzstan' },
  { patterns: [/TAJIKISTAN/i, /\bTJK\b/, /ТОҶИКИСТОН/i], country: 'Tajikistan' },
  { patterns: [/TURKMENISTAN/i, /\bTKM\b/, /TÜRKMENISTAN/i], country: 'Turkmenistan' },
  { patterns: [/BELARUS/i, /\bBLR\b/, /БЕЛАРУСЬ/i], country: 'Belarus' },
  { patterns: [/MOLDOVA/i, /\bMDA\b/], country: 'Moldova' },
  { patterns: [/MONACO/i, /\bMCO\b/], country: 'Monaco' },
  { patterns: [/ANDORRA/i, /\bAND\b/], country: 'Andorra' },
  { patterns: [/SAN\s+MARINO/i, /\bSMR\b/], country: 'San Marino' },
  { patterns: [/VATICAN\s+CITY/i, /\bVAT\b/, /HOLY\s+SEE/i], country: 'Vatican City' },
  { patterns: [/LIECHTENSTEIN/i, /\bLIE\b/], country: 'Liechtenstein' }
];