// This file will be our single source of truth for genre options.

export const GENRE_OPTIONS: string[] = [
    // House Subgenres
    'House',
    'Tech-House',
    'Afro-House',
    'Latin House',
    'Progressive House',
    'Deep House',
    // Techno Subgenres
    'Techno',
    'Hard Techno',
    'Melodic Techno',
    // Trance & Psytrance
    'Trance',
    // Bass Music
    'Dubstep',
    'DnB', // Drum and Bass
    'Trap',
    // Other Electronic Styles
    'Electronic',
    'Tribal',
    'Instrumental',
    // Non-Electronic / Open Format
    'Pop',
    'Rap/Hip-Hop',
];

// --- Airport Codes (Optimized for Fast Lookups) ---

const COMPRESSED_AIRPORT_CODES: string = 'ABE,ABI,ABQ,ABR,ABY,ACK,ACT,ACV,ACY,ADK,ADQ,AEX,AGS,AKN,ALB,ALO,AMA,ANC,APN,ASE,ATL,ATW,AUS,AVL,AVP,AZO,BDL,BET,BFL,BGM,BGR,BHM,BIL,BIS,BJI,BLI,BMI,BNA,BOI,BOS,BPT,BQK,BQN,BRD,BRO,BRW,BTM,BTR,BTV,BUF,BUR,BWI,BZN,CAE,CAK,CDC,CDV,CEC,CHA,CHO,CHS,CID,CIU,CLD,CLE,CLL,CLT,CMH,CMI,CMX,CNY,COD,COS,COU,CPR,CRP,CRW,CSG,CVG,CWA,DAB,DAL,DAY,DBQ,DCA,DEN,DFW,DHN,DIK,DLG,DLH,DRO,DSM,DTW,DUT,EAU,EGE,EKO,ELM,ELP,ERI,ESC,EUG,EVV,EWN,EWR,EYW,FAI,FAR,FAT,FAY,FCA,FLG,FLL,FNT,FSD,FSM,FWA,GCC,GCN,GEG,GFK,GGG,GJT,GNV,GPT,GRB,GRI,GRK,GRR,GSO,GSP,GTF,GTR,GUC,GUM,HDN,HGR,HHH,HIB,HLN,HNL,HOB,HOU,HPN,HRL,HSV,HYA,HYS,IAD,IAG,IAH,ICT,IDA,ILG,ILM,IMT,IND,INL,ISP,ITH,ITO,JAC,JAN,JAX,JFK,JLN,JMS,JNU,KOA,KTN,LAN,LAR,LAS,LAW,LAX,LBB,LBE,LCH,LEX,LFT,LGA,LGB,LIH,LIT,LNK,LSE,LWS,LYH,MAF,MBS,MCI,MCO,MDT,MDW,MEI,MEM,MFE,MFR,MGM,MHT,MIA,MKE,MKG,MLB,MLI,MLU,MMH,MOB,MOT,MQT,MRY,MSN,MSO,MSP,MSY,MTJ,MVY,MYR,OAJ,OAK,OGG,OKC,OMA,OME,ONT,ORD,ORF,ORH,OTH,OTZ,PAH,PBG,PBI,PDX,PHF,PHL,PHX,PIA,PIE,PIH,PIR,PIT,PLN,PNS,PPG,PSC,PSE,PSG,PSM,PSP,PVD,PWM,RAP,RDM,RDU,RHI,RIC,RKS,RNO,ROA,ROC,ROW,RST,RSW,SAN,SAT,SAV,SBA,SBN,SBP,SCC,SCE,SDF,SEA,SFO,SGF,SGU,SHV,SIT,SJC,SJT,SJU,SLC,SMF,SMX,SNA,SPI,SPS,SRQ,STC,STL,STT,STX,SUN,SUX,SWF,SYR,TLH,TOL,TPA,TRI,TUL,TUS,TVC,TWF,TXK,TYR,TYS,VLD,VPS,WRG,XNA,YAK,YUM,YAM,YAY,YAZ,YBB,YBC,YBG,YBK,YBL,YBR,YCD,YCG,YCH,YCL,YDF,YEG,YEV,YFB,YFC,YFO,YFS,YGK,YGL,YGP,YGQ,YGR,YGT,YGW,YGX,YGZ,YHD,YHI,YHM,YHZ,YIO,YIV,YJT,YKA,YKF,YKL,YKM,YKQ,YKS,KU,YLW,YMM,YMO,YMT,YMX,YND,YNG,YNK,YOW,YPE,YPR,YQB,YQC,YQG,YQH,YQI,YQK,YQL,YQM,YQQ,YQR,YQT,YQU,YQX,YQY,YQZ,YRB,YRJ,YRT,YSB,YSC,YSJ,YSM,YSR,YTE,YTH,YTS,YUL,YUX,YUY,YVB,YVC,YVM,YVO,YVP,YVR,YVZ,YWG,YWH,YWK,YWL,YXC,YXD,YXE,YXH,YXJ,YXL,YXS,YXT,YXU,YXX,YXY,YYB,YYC,YYD,YYE,YYF,YYG,YYJ,YYQ,YYR,YYT,YYZ,YZF,YZP,YZR,YZT,YZV,ZBF,ZFA';

let airportCodeSet: Set<string> | undefined;

export const getAirportCodeSet = (): Set<string> => {
    if (!airportCodeSet) {
        airportCodeSet = new Set(COMPRESSED_AIRPORT_CODES.split(','));
    }
    return airportCodeSet;
};